
main:
	gcc -c -o main.o assignment00_Royster_Michael_mainFile.c
	gcc -c -o playerInfo.o assignment00_Royster_Michael_playerInfoFile.c
	gcc -c -o boardInitialization.o assignment00_Royster_Michael_boardInitializationFile.c
	gcc -c -o generations.o assignment00_Royster_Michael_generationsFile.c
	gcc -c -o displayGeneration.o assignment00_Royster_Michael_displayGenerationFile.c
	gcc -c -o readPlayersInformation.o assignment00_Royster_Michael_readPlayersInformationFile.c
	gcc -c -o displayGameSummary.o assignment00_Royster_Michael_displayGameSummaryFile.c
	gcc -c -o printArray.o assignment00_Royster_Michael_printArrayFile.c
	gcc -c -o countPlayers.o assignment00_Royster_Michael_countPlayersFile.c
	gcc -c -o writeFile.o assignment00_Royster_Michael_writeFileFile.c
	gcc -c -o copyArray.o assignment00_Royster_Michael_copyArrayFile.c
	gcc -c -o countActive.o assignment00_Royster_Michael_countActiveFile.c
	gcc -c -o gameOverCheck.o assignment00_Royster_Michael_gameOverCheckFile.c
	gcc -c -o writeFile.o assignment00_Royster_Michael_writeFileFile.c
	gcc -o main main.o playerInfo.o boardInitialization.o generations.o displayGeneration.o readPlayersInformation.o displayGameSummary.o printArray.o copyArray.o writeFile.o countActive.o gameOverCheck.o countPlayers.o

clean:
	rm main
	rm *.o